# Generated by Django 3.2 on 2023-01-29 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=64, verbose_name='text')),
                ('autor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Author')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='post')),
            ],
        ),
    ]
