"""Add user is_displayed

Revision ID: da18e8831db8
Revises: ac6b8aee40a4
Create Date: 2023-01-25 03:43:00.155350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da18e8831db8"
down_revision = "ac6b8aee40a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_displayed", sa.Boolean(), server_default="TRUE", nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_displayed")

    # ### end Alembic commands ###
