version: "3.9"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: homework4
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data: